### ISSUE TITLE
`kubectl logs` not working on isolated network

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/kube-install#1]
we set up [konnectivity](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/) in order for the R2lab nodes, that are not addressable from the `sopnode-*` segment, to be able to join the cluster·s

it seems that the setup is not yet complete
nodes can join indeed, but some commands, like notably
`kubectl logs mypod` 
are found to hang

to be investigated

**Comment by parmentelat** [comment]
I have manually deployed a konnectivity agent on the w2 cluster, but that does not seem to help
this still needs to be double-checked though

**Comment by parmentelat** [comment]
with a pod running on a fit node

* I can't run kubectl logs the-pod from the sopnode network
  symptom is this (after quite a while)
  ```
  Error from server: Get "https://192.168.3.1:10250/containerLogs/default/kiada-fit01-pod/kiada-fit01-cont": dial tcp 192.168.3.1:10250: i/o timeout
  ```
  which is kind of understandable, as 192.168.3.1 is not routable from that location

* however the odd thing is, I get the exact same symptom even when running the logs command from the r2lab network, even the very same node !

**Comment by turletti** [comment]
How can you run the same command (kubectl logs) on a r2lab node? I  get following error:
[root@fit01 ~]# kubectl get no
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by parmentelat** [comment]
you just need to copy `.kube/config` from the master
the latest version of `kube-install.sh join-cluster` will do that for you (although it is still untested)

**Comment by turletti** [comment]
I just tried the command kube-install.sh join-cluster 30mn ago on sopnode-w2 with fit01 but kubectl doesn t work by default. There is no /root/.kube directory. I just copied manually r2lab@sopnode-w2.inria.fr:/home/r2lab/.kube/config and it works

Btw, if I understand correctly, kubectl just interact with a database on the k8s master. So it doesn't seem strange we got the same error from fit nodes

**Comment by parmentelat** [comment]
as an aside, one necessary condition for things to be deemed working is that one should be able to

```
kubectl delete pod <pod-name>
```

from the sopnode cluster when the pod actually runs in R2lab

**Comment by parmentelat** [comment]
testing this with v0.3:

* I still can't access the logs from sopnode-l1 to a pod that runs on fit01
* I can delete the pod though - one has to be patient, but it eventually worked fine

**Comment by parmentelat** [comment]
testing with v0.4, I am still getting
```
sopnode-w1 /usr/share/kube-install (devel=) #
k exec -ti kiada-fit01-pod -- /bin/bash
Error from server: error dialing backend: dial tcp 192.168.3.1:10250: i/o timeout
```

**Comment by parmentelat** [comment]
https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/354

**Comment by parmentelat** [comment]
it appears our konnectivity agent is ill-configured
```
k describe daemonsets.apps konnectivity-agent
<snip>
Events:
  Type     Reason        Age                   From                  Message
  ----     ------        ----                  ----                  -------
  Warning  FailedCreate  7m3s (x194 over 19h)  daemonset-controller  Error creating: pods "konnectivity-agent-" is forbidden: error looking up service account kube-system/konnectivity-agent: serviceaccount "konnectivity-agent" not found
```

**Comment by parmentelat** [comment]
having fixed the misconfiguration, (by injecting the missing rbac rules), 
and having rebuilt the cluster from scratch, what I can see now is

* I have 3 nodes in the cluster
  * l1 (leader, on the A side)
  * w1 (worker, also on the A side)
  * fit01 (worker, on the B side)
* the konnectivity daemonset is now fine; however it has created 2 pods:
  * one on w1 (works fine) and
  * one on fit01, that won't start and is in `ContainerCreating` state
* here's how this failing pod describes

  ```
  # k describe pod konnectivity-agent-cwvvn
  <snip>
  Warning  FailedCreatePodSandBox  3m13s (x84 over 21m)  kubelet            (combined from similar events): 
  Failed to create pod sandbox:
   rpc error: code = Unknown desc = failed to create pod network sandbox k8s_konnectivity-agent-cwvvn_kube-system_c2e67df7-4d64-48ac-abb0-8ead5e90350d_0(012375d085941c968265627a8740b7994ab4a9ad8f25a0e2f8ae85fb20135106): 
  error adding pod kube-system_konnectivity-agent-cwvvn to CNI network "cbr0":
  failed to delegate add:
  failed to set bridge addr: "cni0" already has an IP address different from 10.244.2.1/24
  ```

**Comment by turletti** [comment]
Je ne sais pas si c'est lié mais pour lancer oai5g hier, j'ai dû installer multus. multus est aussi indispensble pour lancer aether. Cette librairie permet de gerer plusieurs interfaces réseau par pod. Lorsque tu as fait tes essais ce matin, le cluster k8s tournait multus.

**Comment by parmentelat** [comment]
I have rebuilt the cluster from scratch before all this

**Comment by parmentelat** [comment]
also here's iptables output
```
[root@fit01 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-NODEPORTS  all  --  anywhere             anywhere             /* kubernetes health check service ports */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
KUBE-FORWARD  all  --  anywhere             anywhere             /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes externally-visible service portals */
ACCEPT     all  --  10.244.0.0/16        anywhere             /* flanneld forward */
ACCEPT     all  --  anywhere             10.244.0.0/16        /* flanneld forward */

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  anywhere             anywhere             ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  anywhere             anywhere

Chain KUBE-EXTERNAL-SERVICES (2 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
DROP       all  -- !localhost/8          localhost/8          /* block incoming localnet connections */ ! ctstate RELATED,ESTABLISHED,DNAT

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere             ctstate INVALID
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere             /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-NODEPORTS (1 references)
target     prot opt source               destination

Chain KUBE-PROXY-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-SERVICES (2 references)
target     prot opt source               destination
```

**Comment by parmentelat** [comment]
une autre commande qui tombe dans le même trou: `kubectl cp` qui ne marche pas mieux que les autres...
