### ISSUE TITLE
Installation de multus/calico 

### ISSUE THREAD

**Issue by turletti** [parmentelat/kube-install#12]
Une fois que konnectivity fonctionne et qu'on sait redémarrer le cluster de manière reproductible, j'aimerais essayer cette version de multus (calico) qui est préconisée pour aether avec des devices 5G réels (pas émulés).

https://github.com/k8snetworkplumbingwg/reference-deployment/tree/master/multus-calico

Il faudra que je vérifie que c est compatible avec les pods de oai5g et que ca marche bien avec aether.

Pour ne pas géner tout le reste, il faudrait faire cet essai sur un cluster tout neuf et le resetter à la fin en cas de soucis.

**Comment by parmentelat** [comment]
This is something that can be done separately at a user level, so it won't be made a part of kube-install
