### ISSUE TITLE
check compatibility with aether-in-a-box

### ISSUE THREAD

**Issue by parmentelat** [parmentelat/kube-install#3]
looks like aether-in-a-box comes with the following settings

```
            -e "{'override_system_hostname' : False, 'disable_swap' : True}" \
            -e "{'docker_iptables_enabled' : True}" \
            -e "{'kube_network_plugin_multus' : True, 'multus_version' : stable, 'multus_cni_version' : 0.3.1}" \
    -e "{'kube_proxy_metrics_bind_address' : 0.0.0.0:10249}" \
        -e "{'kube_pods_subnet' : 192.168.0.0/17, 'kube_service_addresses' : 192.168.128.0/17}" \
            -e "{'kube_apiserver_node_port_range' : 2000-36767}" \
    -e "{'kubeadm_enabled': True}" \
            -e "{'kube_feature_gates' : [SCTPSupport=True]}" \
        -e "{'kubelet_custom_flags' : [--allowed-unsafe-sysctls=net.*]}" \
            -e "{'dns_min_replicas' : 1}" \
        -e "{'helm_enabled' : True, 'helm_version' : $(HELM_VERSION)}" \

```

we may need to either ensure our clusters fulfil these requirements, or at least that we have a means to configure it this way

**Comment by turletti** [comment]
Regarding part of the parameters above, I got a few answers from https://onf-community.slack.com/team/U013J9NRRFU

- regarding multus, it has to be multus/calico, see open issue #12 
- regarding 'kube_pods_subnet' : 192.168.0.0/17, 'kube_service_addresses' : 192.168.128.0/17 , this should be a problem to use default setup
- regarding 'kube_apiserver_node_port_range' : 2000-36767 , some pods won't start without that (e.g. mme pod from omec). I already tried to add the option - --service-node-port-range=2000-36767 in /etc/kubernetes/manifests/kube-apiserver.yaml and it works well. ==> I guess we could use this range as default in our setup
